name: PR checks

on:
  push:
    paths:
      - pyproject.toml
      - '**.py'
  pull_request:
    paths:
      - pyproject.toml
      - '**.py'

jobs:
  lint:
    name: 'ruff & mypy & pytest'
    runs-on: riscv-builders
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install --with=dev
      - name: Lint with ruff
        run: poetry run ruff check
      - name: Type-check with mypy
        run: poetry run mypy
      - name: Test with pytest
        run: poetry run pytest
